# Generated by Django 5.1.4 on 2025-01-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('white_player', models.CharField(blank=True, max_length=100, null=True)),
                ('black_player', models.CharField(blank=True, max_length=100, null=True)),
                ('White_FideId', models.IntegerField(blank=True, null=True)),
                ('Black_FideId', models.IntegerField(blank=True, null=True)),
                ('white_elo', models.IntegerField(blank=True, null=True)),
                ('black_elo', models.IntegerField(blank=True, null=True)),
                ('white_title', models.CharField(blank=True, max_length=5, null=True)),
                ('black_title', models.CharField(blank=True, max_length=5, null=True)),
                ('result', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('site', models.CharField(blank=True, max_length=200, null=True)),
                ('round', models.CharField(blank=True, max_length=50, null=True)),
                ('eco', models.CharField(blank=True, max_length=10, null=True)),
                ('notation', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ChessGame',
        ),
    ]
