# Generated by Django 5.1.4 on 2025-01-08 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_game_delete_chessgame'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='Black_FideId',
            new_name='black_FideId',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='White_FideId',
            new_name='white_FideId',
        ),
    ]
