services:
  redis:
    image: redis:7.0.11

  django:
    container_name: Django
    build: 
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/usr/src/app/
    ports: 
      - 8001:8000
    env_file:
      - .env
    depends_on:
      - redis

  celery:
    container_name: celery
    build: 
      context: .
    command: celery --app=chesshub_project worker -l INFO --concurrency=10
    volumes: 
      - .:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - redis
      - django