services:
  redis:
    image: redis:7.0.11
    env_file:
    - .env

  django:
    container_name: Django
    build: 
      context: .
    command: uvicorn chesshub_project.asgi:application --host 0.0.0.0 --port 8000 --workers 4
    volumes: 
      - .:/usr/src/app/
    ports: 
      - 8001:8000
    env_file:
      - .env
    depends_on:
      - redis

  celery-upload:
    container_name: celery-upload
    build: 
      context: .
    command: celery --app=chesshub_project worker -l INFO --concurrency=3 -Q upload_queue
    volumes: 
      - .:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - redis

  celery-fetch:
    container_name: celery-fetch
    build: 
      context: .
    command: celery --app=chesshub_project worker -l INFO --concurrency=1 -Q fetch_queue
    volumes: 
      - .:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - redis

  celery-process:
    container_name: celery-process
    build: 
      context: .
    command: celery --app=chesshub_project worker -l INFO --concurrency=2 -Q process_queue
    volumes: 
      - .:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - redis

  celery-chunk:
    container_name: celery-chunk
    build: 
      context: .
    command: celery --app=chesshub_project worker -l INFO --concurrency=10 -Q chunk_queue
    volumes: 
      - .:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - redis
  
  celery-beat:
    container_name: celery-beat
    build: 
      context: .
    command: celery --app=chesshub_project beat --loglevel=info
    volumes: 
      - .:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - redis