services:
  redis:
    image: redis:7.0.11
    env_file:
    - .env

  django:
    container_name: Django
    build: 
      context: .
    command: uvicorn chesshub_project.asgi:application --host 0.0.0.0 --port 8000 --workers 4
    volumes: 
      - .:/usr/src/app/
    ports: 
      - 8001:8000
    env_file:
      - .env
    depends_on:
      - redis

  celery-upload:
    container_name: celery-upload
    build: 
      context: .
    command: celery --app=chesshub_project worker -l INFO --concurrency=3 -Q upload_queue -n chunk_worker@%h
    volumes: 
      - .:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - redis
      - django

  celery-fetch:
    container_name: celery-fetch
    build: 
      context: .
    command: celery --app=chesshub_project worker -l INFO --concurrency=1 -Q fetch_queue -n chunk_worker@%h
    volumes: 
      - .:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - redis
      - django

  celery-process:
    container_name: celery-process
    build: 
      context: .
    command: celery --app=chesshub_project worker -l INFO --concurrency=2 -Q process_queue -n chunk_worker@%h
    volumes: 
      - .:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - redis
      - django

  celery-chunk:
    container_name: celery-chunk
    build: 
      context: .
    command: celery --app=chesshub_project worker -l INFO --concurrency=10 -Q chunk_queue -n chunk_worker@%h
    volumes: 
      - .:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - redis
      - django
  
  celery-beat:
    container_name: celery-beat
    build: 
      context: .
    command: celery --app=chesshub_project beat --loglevel=info
    volumes: 
      - .:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - django
      - redis

  celery-beat-worker:
    container_name: celery-beat-worker
    build: 
      context: .
    command: celery --app=chesshub_project worker --loglevel=INFO --concurrency=1 -Q beat_queue
    volumes: 
      - .:/usr/src/app/
    env_file:
      - .env
    depends_on:
      - redis
      - django
    
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: chessuser
      POSTGRES_PASSWORD: chesspass
      POSTGRES_DB: chessuser
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data: